"""empty message

Revision ID: 716f69721994
Revises: 10b12b3aa968
Create Date: 2021-05-16 15:27:58.966942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716f69721994'
down_revision = '10b12b3aa968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('income', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'income')
    # ### end Alembic commands ###
