"""empty message

Revision ID: 5f099f8c331c
Revises: 361e4a64bafc
Create Date: 2021-05-05 19:02:35.324552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f099f8c331c'
down_revision = '361e4a64bafc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('sub_category', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'sub_category')
    # ### end Alembic commands ###
