"""empty message

Revision ID: 361e4a64bafc
Revises: 860a2f2be4a2
Create Date: 2021-05-05 14:25:17.448617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361e4a64bafc'
down_revision = '860a2f2be4a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_categories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=False),
                    sa.Column('sub_category', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['category_id'], ['categories.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_categories')
    # ### end Alembic commands ###
