"""empty message

Revision ID: 860a2f2be4a2
Revises: a69a16a9195c
Create Date: 2021-05-05 12:31:20.762890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '860a2f2be4a2'
down_revision = 'a69a16a9195c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Categories')
    op.create_foreign_key(None, 'bills', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'bills', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'budgets', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'budgets', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.drop_constraint(None, 'bills', type_='foreignkey')
    op.drop_constraint(None, 'bills', type_='foreignkey')
    op.create_table('Categories',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Categories_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Categories_pkey')
    )
    op.drop_table('categories')
    # ### end Alembic commands ###
