"""empty message

Revision ID: 10b12b3aa968
Revises: 5f099f8c331c
Create Date: 2021-05-10 19:03:15.262187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b12b3aa968'
down_revision = '5f099f8c331c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('sub_category', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'sub_category')
    # ### end Alembic commands ###
